server:
  port: 8003

spring:
  application:
    name: springcloud-concul-provider-8003
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db05?useUnicode=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}



mybatis:
  type-aliases-package: com.ycz.com.ycz.com.ycz.com.ycz.springCloud.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

